a = input('Digite algo:')
print('O tipo primitivo desse valor e',type(a))
print('So tem espacoes?',a.isspace())
print('E um numero?',a.isnumeric())
print('E alfabetico?',a.isalpha())
print('E alfanumerico?',a.isalnum())
print('Esta em maiuscula?',a.isupper())
print('Esta em minuscula?',a.islower())
print('Esta capiatalizada?',a.istitle())
